######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 23 12:34:00 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += visHang.h
SOURCES += main.cpp visHang.cpp
